name = "CommitCraft"
language = "Python"
description = """
CommitCraft is an innovative tool designed to enhance the quality of your Git commit messages by leveraging artificial intelligence (AI). 
It automatically generates summaries and commit messages based on the changes introduced in a pull request or commit, making it easier for developers to communicate what's been updated in their code.
The project aims to streamline the development process by providing AI-driven suggestions that are tailored to specific contexts and features added or modified within the repository.
"""
guidelines = """
Create concise and understandable commit messages, be direct about what chasnged and why, give a small summary
of what has changed and how it may afect the rest of the project. Do not return any explanation other then the commit message itself.
"""
emoji="""
Chose one of the folowing emoji to start you message, use just the emoji, and only if the description applies to the diff, you should then describe the changes, use the format "emoji commit message title \n rest of the message":
    ğŸ¨ ; Improve structure / format of the code.
    âš¡ï¸ ; Improve performance.
    ğŸ”¥ ; Remove code or files.
    ğŸ› ; Fix a bug.
    ğŸš‘ï¸ ; Critical hotfix.
    âœ¨ ; Introduce new features.
    ğŸ“ ; Add or update documentation.
    ğŸš€ ; Deploy stuff.
    ğŸ’„ ; Add or update the UI and style files.
    ğŸ‰ ; Begin a project.
    âœ… ; Add, update, or pass tests.
    ğŸ”’ï¸ ; Fix security or privacy issues.
    ğŸ” ; Add or update secrets.
    ğŸ”– ; Release / Version tags.
    ğŸš¨ ; Fix compiler / linter warnings.
    ğŸš§ ; Work in progress.
    ğŸ’š ; Fix CI Build.
    â¬‡ï¸ ; Downgrade dependencies.
    â¬†ï¸ ; Upgrade dependencies.
    ğŸ“Œ ; Pin dependencies to specific versions.
    ğŸ‘· ; Add or update CI build system.
    ğŸ“ˆ ; Add or update analytics or track code.
    â™»ï¸ ; Refactor code.
    â• ; Add a dependency.
    â– ; Remove a dependency.
    ğŸ”§ ; Add or update configuration files.
    ğŸ”¨ ; Add or update development scripts.
    ğŸŒ ; Internationalization and localization.
    âœï¸ ; Fix typos.
    ğŸ’© ; Write bad code that needs to be improved.
    âªï¸ ; Revert changes.
    ğŸ”€ ; Merge branches.
    ğŸ“¦ï¸ ; Add or update compiled files or packages.
    ğŸ‘½ï¸ ; Update code due to external API changes.
    ğŸšš ; Move or rename resources (e.g.: files, paths, routes).
    ğŸ“„ ; Add or update license.
    ğŸ’¥ ; Introduce breaking changes.
    ğŸ± ; Add or update assets.
    â™¿ï¸ ; Improve accessibility.
    ğŸ’¡ ; Add or update comments in source code.
    ğŸ» ; Write code drunkenly.
    ğŸ’¬ ; Add or update text and literals.
    ğŸ—ƒï¸ ; Perform database related changes.
    ğŸ”Š ; Add or update logs.
    ğŸ”‡ ; Remove logs.
    ğŸ‘¥ ; Add or update contributor(s).
    ğŸš¸ ; Improve user experience / usability.
    ğŸ—ï¸ ; Make architectural changes.
    ğŸ“± ; Work on responsive design.
    ğŸ¤¡ ; Mock things.
    ğŸ¥š ; Add or update an easter egg.
    ğŸ™ˆ ; Add or update a .gitignore file.
    ğŸ“¸ ; Add or update snapshots.
    âš—ï¸ ; Perform experiments.
    ğŸ”ï¸ ; Improve SEO.
    ğŸ·ï¸ ; Add or update types.
    ğŸŒ± ; Add or update seed files.
    ğŸš© ; Add, update, or remove feature flags.
    ğŸ¥… ; Catch errors.
    ğŸ’« ; Add or update animations and transitions.
    ğŸ—‘ï¸ ; Deprecate code that needs to be cleaned up.
    ğŸ›‚ ; Work on code related to authorization, roles and permissions.
    ğŸ©¹ ; Simple fix for a non-critical issue.
    ğŸ§ ; Data exploration/inspection.
    âš°ï¸ ; Remove dead code.
    ğŸ§ª ; Add a failing test.
    ğŸ‘” ; Add or update business logic.
    ğŸ©º ; Add or update healthcheck.
    ğŸ§± ; Infrastructure related changes.
    ğŸ§‘â€ğŸ’» ; Improve developer experience.
    ğŸ’¸ ; Add sponsorships or money related infrastructure.
    ğŸ§µ ; Add or update code related to multithreading or concurrency.
    ğŸ¦º ; Add or update code related to validation.
"""